[build]
  publish = "static"
  functions = "functions"
  command = "npm run build"

[[redirects]]
  from = "/sales"
  to = "/.netlify/functions/sales"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}
