[build]
  publish = "static"
  functions = "functions"
  command = "npm run build"

[[redirects]]
  from = "/sales"
  to = "/.netlify/functions/sales"
  status = 200

[[headers]]
  for = "/.netlify/functions/sales"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET"

[[headers]]
  for = "/sales"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET"
